import { Navbar } from '@/components/navigation/Navbar'
import './styles.css'
import { Metadata } from 'next'
import { getPayload } from 'payload'
import config from '@/payload.config'

interface HomepageProps {
  params: Promise<{
    locale: string
  }>
}

export async function generateMetadata({ params }: HomepageProps): Promise<Metadata> {
  const { locale } = await params
  const payload = await getPayload({ config })

  const result = await payload.find({
    collection: 'pages',
    locale: locale as any,
    where: {
      slug: { equals: 'index' },
    },
    limit: 1,
  })

  // Cast as 'any' to easily read plugin fields without strict local type compilation errors
  const pageData = result.docs[0] as any

  // 💡 Extract the deeply nested fields generated by the Payload SEO plugin
  const seoTitle = pageData?.meta?.title
  const seoDescription = pageData?.meta?.description
  const seoImage = pageData?.meta?.image?.url

  return {
    // Priority 1: Use the dedicated Admin SEO title
    // Priority 2: Fall back to the internal Page Title + Suffix
    // Priority 3: Final hardcoded fallback string
    title: seoTitle || (pageData?.title ? `${pageData.title} | Studio` : 'Studio Engine'),
    description: seoDescription || 'Next-gen enterprise software and design systems architecture.',

    // Optional: map your SEO open-graph sharing image automatically!
    openGraph: seoImage
      ? {
          images: [{ url: seoImage }],
        }
      : undefined,
  }
}

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode
  params: Promise<{ locale: string }>
}) {
  const { locale } = await params

  return (
    <html lang={locale} className="bg-zinc-950 text-white">
      <body className="antialiased selection:bg-indigo-500/30 selection:text-indigo-200">
        <Navbar locale={locale} />
        {children}
      </body>
    </html>
  )
}
